BikeShop/Models/ErrorViewModel.cs
namespace BikeShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BikeShop/Controllers/AccountController.cs
using Bikeshop.Application.Command;
using Bikeshop.Application.Query;
using Bikeshop.Application.ViewModel;
using BikeWebshop.Application.Interfaces;
using Domain.Persistence;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BikeShop.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult LoginPage()
        {
            return View();
        }

        public IActionResult RegisterPage()
        {
            return View();
        }

        IShopContext _context;
        IMediator _mediator;
        UserManager<IdentityUser> _userManager;
        SignInManager<IdentityUser> _signInManager;
        RoleManager<IdentityRole> _roleManager;
        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager,  IMediator mediator, IShopContext context, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _mediator = mediator;
            _context = context;
            _roleManager = roleManager;
        }
        public async Task<IActionResult> Register([FromForm] Login model)
        {
            var user = new IdentityUser { UserName = model.UserName, PasswordHash = model.Password };
            var result = _userManager.CreateAsync(user, model.Password);
            if (!result.Result.Succeeded)
            {
                return BadRequest(result.Result.Errors);
            }
            if (user.UserName != "Admin")
            {
                var admin = _roleManager.FindByNameAsync("Customer").Result;
                IdentityResult roleresult = await _userManager.AddToRoleAsync(user, admin.Name);
                Customer customer = new Customer(userName: user.UserName, identityUser: user, email: model.Email);
                //var command = new CreateCustomerCommand(customer);
                //await _mediator.Send(command);
                ShoppingBag shoppingBag = new ShoppingBag(customer, DateTime.Now);
                var command2 = new CreateShoppingBagCommand(shoppingBag);
                await _mediator.Send(command2);
            }
            if (user.UserName == "Admin")
            {
                var customer = _roleManager.FindByNameAsync("Admin").Result;
                IdentityResult roleresult = await _userManager.AddToRoleAsync(user, customer.Name);
            }
            return RedirectToAction("LoginPage", "Account");
        }

        public async Task<IActionResult> Login([FromForm] Login login)
        {
            var user = await _userManager.FindByNameAsync(login.UserName);
            var result = await _signInManager.PasswordSignInAsync(user, login.Password, true, false);

            if (result.Succeeded)
            {
                return LocalRedirect("/Product");
            }
            return LocalRedirect("");
        }

        [Route("Logout")]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        public IActionResult Privacy()
        {
            return Ok();
        }
    }
}

BikeShop/Controllers/AdministratorController.cs
using Bikeshop.Application.Command;
using Bikeshop.Application.Query;
using Bikeshop.Application.ViewModel;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using BikeWebshop.Application.Interfaces;
using Domain.Persistence;
using Microsoft.AspNetCore.Authorization;

namespace BikeShop.Controllers
{
    public class AdministratorController : Controller
    {
        IMediator _mediator;
        public AdministratorController(IMediator mediator)
        {
            _mediator = mediator;
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> NewBike()
        {
            return View();
        }

        public async Task<IActionResult> AddBike([FromForm] Product product)
        {
            if (product.CheckRegistration(product.RegistrationNumber))
            {
                var command = new CreateProductCommand(product);
                await _mediator.Send(command);
                return Redirect("/");
            }
            return Redirect("/Administrator/NewBike");
        }
    }
}

BikeShop/Controllers/HomeController.cs
using BikeShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BikeShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Random r = new Random();
            ViewData["randomNumber"] = r.Next(1, 5);
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BikeShop/Controllers/ProductController.cs
using Bikeshop.Application.Command;
using Bikeshop.Application.Query;
using Bikeshop.Application.ViewModel;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using BikeWebshop.Application.Interfaces;
using Domain.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;

namespace BikeShop.Controllers
{
    public class ProductController : Controller
    {
        IMediator _mediator;
        IShopContext _context;
        UserManager<IdentityUser> _userManager;
        private readonly ILogger<ProductController> _logger;
        public ProductController(UserManager<IdentityUser> userManager, IMediator mediator, IShopContext shopContext, ILogger<ProductController> logger)
        {
            _mediator = mediator;
            _context = shopContext;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var query = new ShowAllProductsQuery();
            var products = await _mediator.Send(query);
            return View(products);
        }

        public async Task<IActionResult> Details(int id)
        {
            var query = new ShowProductByIdQuery(id);
            ViewData["product"] = await _mediator.Send(query);
            return View();
        }

        public async Task<IActionResult> Shop([Bind("ProductID,Quantity")] ShoppingItemVM shoppingItem)
        {
            string userId = _userManager.GetUserId(HttpContext.User);
            var query = new ShowCustomerByUserIdQuery(userId);
            var customer = await _mediator.Send(query);
            var shoppingBag = _context.ShoppingBags.Where(j => j.CustomerID == customer.Id)
                  .OrderByDescending(a => a.Id)
                  .Select(p => p).FirstOrDefault();
            shoppingItem.ShoppingBagID = shoppingBag.Id;
            var command = new CreateShoppingItemCommand(shoppingItem);
            await _mediator.Send(command);
            _logger.LogDebug("item to shoppingbag");

            return LocalRedirect("/Product");
        }

        public async Task<IActionResult> Bag()
        {
            string userId = _userManager.GetUserId(HttpContext.User);
            var query = new ShowShoppingBagInfoByIdQuery(1);
            var shoppingBagData = await _mediator.Send(query);
            ViewData["Discount"] = getDiscount(shoppingBagData);
            return View(shoppingBagData);
        }

        public double getDiscount(ShoppingBag shoppingBag)
        {
            double productCount = 0;
            foreach(ShoppingItem shoppingItem in shoppingBag.Items) 
            {
                productCount += shoppingItem.Quantity;
            }
            switch (productCount)
            {
                case < 3:
                    return 0;
                case >= 3 and < 6:
                    return 5;
                case >= 6:
                    return 10;
            }
            return 0;
        }
    }
}

BikeShop/Views/Administrator/NewBike.cshtml
@using Bikeshop.Application.ViewModel;
@model ProductVM 
@{
    ViewData["Title"] = "Add Bike";
}
<h1>New Bike</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddBike" asp-controller="Administrator" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegistrationNumber" class="control-label"></label>
                <input asp-for="RegistrationNumber" class="form-control" />
                <span asp-validation-for="RegistrationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="AddBike" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BikeShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    string url = "/Images/Bike" + ViewData["randomNumber"] + ".jfif";
}

<div class="text-center">
    <h1 class="display-4">Welcome Customer</h1>
    <a asp-controller="Product" asp-action="Index"><img width="500px" class="mt-5" src="@url" /></a>
</div>

BikeShop/Views/Product/Bag.cshtml
@using Domain.Persistence;
@model ShoppingBag
@{
    var shoppingBagData = ViewData["shoppingBag"];
    var discountString = ViewData["Discount"].ToString();
    double discount = int.Parse(discountString);
}
<h1>Shopping bag @Model.Customer.UserName</h1>
<table>
    @{
        double amount = 0; double itemAmount = 0;
    }
    @foreach(var shoppingItem in Model.Items)
    {
        amount += shoppingItem.Product.Price * shoppingItem.Quantity;
        itemAmount += shoppingItem.Quantity;
        <tr>
            <td class="border-1 text-center px-2" width="100px">@shoppingItem.Product.Name</td>
            <td class="border-1 text-center px-2" width="100px">@shoppingItem.Quantity</td>
        </tr>
    }
</table>
@{
    var finalCount = (amount * (100 - discount)) / 100;
}
<p>@finalCount with a @discount % discount</p>

BikeShop/Views/Product/Details.cshtml
@using Bikeshop.Application.ViewModel;
@using Domain.Persistence;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;
@model ShoppingItem
@{
    ProductVM product = ViewBag.product;
}
<h1>@product.Name</h1>
@if (!signInManager.IsSignedIn(User))
{
    <h2>Sing in to view our product</h2>
}
@if (signInManager.IsSignedIn(User))
{
   <form asp-action="Shop">
    <div>
        <label>Quantity</label>
        <input asp-for="Quantity" type="number" />
    </div>
    <input type="hidden" value="@product.Id" asp-for="ProductID" />
    <button type="submit">Submit</button>
    </form>
}

BikeShop/Views/Product/Index.cshtml
@using Bikeshop.Application.ViewModel;
@using Domain.Persistence;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;

@model ListProductVM
@{
}

<h1>Products</h1>
<div class="container">
    <div>
        @if (signInManager.IsSignedIn(User))
        {
            <div class="d-flex w-full justify-content-around mt-5 flex-wrap">
                @foreach (ProductVM product in Model.Products)
                {
                    <div class="pb-0 pt-3 px-3 border m-3 cardW">
                        <p class="text-center w-full font-weight-bold">@product.Name</p>
                        <a class="fullW bg-success text-light p-2 rounded fullWIdth" asp-action="Details" asp-route-id="@product.Id">Buy</a>
                        <p class="text-center w-full font-weight-bold mt-3">€@product.Price</p>
                    </div>
                }
            </div>
        }   
    </div>
</div>

<style>
    .cardW {width: 250px}
    .fullW {width: 100%}
</style>

BikeShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BikeShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BikeShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BikeShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Bag">ShoppingBag</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="NewBike">Add Bike</a>
                            </li>
                        }
                    </ul>
                    @if (!signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav float-right">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="RegisterPage">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LoginPage">Login</a>
                            </li>
                        </ul>
                    }
                    @if (signInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav float-right">
                            <li class="nav-item">
                                <a asp-controller="Account" asp-action="Logout" class="nav-link btn btn-link text-dark">Logout</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BikeShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>